accounts/urls.py
from django.urls import path
from .views import login, logout


urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
]


games/urls.py
from django.urls import path
from .views import home, CategoriaCreateView, create_game, edit_game, delete_game, relatorio_A, relatorio_B


urlpatterns = [
    path('', home, name='home'),
    path('categoria/new', CategoriaCreateView.as_view(), name='categoria_new'),
    path('game/new', create_game, name='game_new'),
    path('game/edit/<int:pk>', edit_game, name='game_edit'),
    path('game/delete/<int:pk>', delete_game, name='game_delete'),
    path('relatorio-a', relatorio_A, name='relatorio_A'),
    path('relatorio-b', relatorio_B, name='relatorio_B'),
]


setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('games.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

games/models.py
from django.db import models


class Categoria(models.Model):
    descricao = models.CharField(max_length=100)

    def __str__(self):
        return self.descricao


class Game(models.Model):
    nome = models.CharField(max_length=150)
    categoria = models.ForeignKey(Categoria, on_delete=models.PROTECT, related_name="game_categoria")


class ReportPermissions(models.Model):
    class Meta:
        abstract = True
        # mesmo que esteja no arquivo migrate de forma manual, bom referenciar aqui
        permissions = (
            ('view_report_a', "Ver relatorio A"),
            ('view_report_b', "Ver relatorio B")
        )

games/forms.py
from django import forms

from games.models import Game, Categoria


class CategoriaForm(forms.ModelForm):
    
    class Meta:
        model = Categoria
        fields = '__all__'


class GameForm(forms.ModelForm):
    
    class Meta:
        model = Game
        fields = '__all__'

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import auth, messages


def login(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('home')

    if request.method == 'POST':
        username = request.POST['username']
        senha = request.POST['senha']

        if username == "" or senha == "":
            messages.error(request, "Campos username e senha não podem ficar em branco!")
            return redirect('login')
        user = auth.authenticate(request, username=username, password=senha)

        if user is not None:
            auth.login(request, user)
            proxima_pagina = request.POST.get('next')
            if proxima_pagina:
                return redirect(proxima_pagina)
            return redirect('home')
        else:
            messages.error(request, "username/senha estão incorretos")
            return render(request, 'login.html')

    return render(request, 'login.html')


def logout(request):
    """ Realiza logout do usuário """
    auth.logout(request)
    return redirect('login')

games/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.http import HttpResponse

from games.forms import CategoriaForm, GameForm
from games.models import Game


@login_required
def home(request):
    games = Game.objects.select_related('categoria').all()
    data = {'games': games}
    return render(request, 'games.html', data)

@permission_required('games.add_game', raise_exception=True)
def create_game(request):
    form = GameForm(request.POST or None)

    if request.POST:
        if form.is_valid():
            form.save()
            return redirect('home')

    data = {'form': form}

    return render(request, 'game.html', data)

@permission_required('games.change_game', raise_exception=True)
def edit_game(request, pk):
    game = get_object_or_404(Game, id=pk)
    form = GameForm(request.POST or None, instance=game)

    if request.POST:
        if form.is_valid():
            form.save()
            return redirect('home')

    data = {'form': form}

    return render(request, 'game.html', data)

@permission_required('games.delete_game', raise_exception=True)
def delete_game(request, pk):
    game = get_object_or_404(Game, id=pk)
    game.delete()
    return redirect('home')

@permission_required('games.view_report_a', raise_exception=True)
def relatorio_A(request):
    return HttpResponse('Relatorio A')

@permission_required('games.view_report_b', raise_exception=True)
def relatorio_B(request):
    return HttpResponse('Relatorio B')


class CategoriaCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    template_name = 'categoria.html'
    form_class = CategoriaForm
    success_url = reverse_lazy('home')
    success_message = "Categoria cadastrado com sucesso"

templates/_alertas.html
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}" role="alert">
        {{ message }}
    </div>
    {% endfor %}
{% endif %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sistema</title>
</head>
<body>
<a href="{% url 'home' %}">Home</a>

{% block content %}

{% endblock %}


</br>
Lista de Jogos:
{% if perms.games.view_game %}

<table class="table">
    
    <thead>
        <tr>
        <th>
            ID
        </th>
        <th>
            Nome
        </th>
        <th>
            Categorias
        </th>

        <th>Ações</th>
        </tr>
    </thead>
    <tbody>

    {% for game in games %}
        <tr>
            <td> 
                <a href="{% url 'game_edit' pk=game.id %}">{{ game.id }}</a>
            </td>
            <td> {{ game.nome }}</td>
            <td>
                {{ game.categoria }}
            </td>
            <td> 
                <a href="{% url 'game_delete' pk=game.id %}">Deletar</a>
            </td>
        </tr>
        {% endfor %}

    
    </tbody>
    
    </table>

</body>

{% else %}
sem permissao pra ver lista de games!!!

{% endif %}

{% if user.is_authenticated %}
<a href="{% url 'logout' %}">Logout</a>
{% endif %}
</html>

templates/categoria.html
{% extends 'base.html' %}

{% block content %}


<h2>Categoria</h2>

<form method="POST">
    {% csrf_token %}
    {% for field in form %}
    <p>{{ field.label_tag }} {{ field }} </p>
    {% if form.errors %}
    {% for error in field.errors %}
    <p class="alert alert-danger">
        <strong>{{ error|escape }}</strong>
    </p>
    {% endfor %}
    {% endif %}
    {% if field.help_text %}
    <p class="form-text">{{ field.help_text|safe }}</p>
    {% endif %}
    {% endfor %}

    <button type="submit" class="btn btn-primary">Salvar</button>

</form>

{% endblock %}

templates/game.html
{% extends 'base.html' %}

{% block content %}


<h2>Game</h2>

<form method="POST">
    {% csrf_token %}
    {% for field in form %}
    <p>{{ field.label_tag }} {{ field }} </p>
    {% if form.errors %}
    {% for error in field.errors %}
    <p class="alert alert-danger">
        <strong>{{ error|escape }}</strong>
    </p>
    {% endfor %}
    {% endif %}
    {% if field.help_text %}
    <p class="form-text">{{ field.help_text|safe }}</p>
    {% endif %}
    {% endfor %}

    <button type="submit" class="btn btn-primary">Salvar</button>

</form>


{% endblock %}

templates/games.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'categoria_new' %}">Categoria</a>

{% if perms.games.view_game %}
<a href="{% url 'game_new' %}">Games</a>
{% else %}
sem permissao para add games!
{% endif %}

{% if perms.games.view_report_a %}
<a href="{% url 'relatorio_A' %}">Relatorio A</a>
{% else %}
sem permissao para relatorio A
{% endif %}

{% if perms.games.view_report_b %}
<a href="{% url 'relatorio_B' %}">Relatorio B</a>
{% else %}
sem permissao para relatorio B
{% endif %}


{% endblock %}

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Login </title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/signin.css' %}" rel="stylesheet">
</head>

<body class="text-center">

  <svg xmlns="http://www.w3.org/2000/svg" style="display: none;" >
    <symbol id="turismo-shared" viewBox="0 0 16 16">
      <path d="M7 7V1.414a1 1 0 0 1 2 0V2h5a1 1 0 0 1 .8.4l.975 1.3a.5.5 0 0 1 0 .6L14.8 5.6a1 1 0 0 1-.8.4H9v10H7v-5H2a1 1 0 0 1-.8-.4L.225 9.3a.5.5 0 0 1 0-.6L1.2 7.4A1 1 0 0 1 2 7h5zm1 3V8H2l-.75 1L2 10h6zm0-5h6l.75-1L14 3H8v2z"/>
    </symbol>
  </svg>
  <main class="form-signin">
    <form id="login" action="{% url 'login' %}" method="POST">
      {% csrf_token %}
      <input type="hidden" name="next" value="{{ request.GET.next }}" />

      <svg class="bi me-2" width="72" height="57" role="img" aria-label="Turismo-Shared"><use xlink:href="#turismo-shared"/></svg>
      <h1 class="h3 mb-3 fw-normal">Loja</h1>
      {% include '_alertas.html' %}

      <div class="form-floating">
        <input name="username" type="text" class="form-control" id="floatingInput" placeholder="myuser">
        <label for="floatingInput">Username</label>
      </div>
      <div class="form-floating">
        <input name="senha" type="password" class="form-control" id="floatingPassword" placeholder="Senha">
        <label for="floatingPassword">Senha</label>
      </div>

      <div class="checkbox mb-3">
        <label>
          <input id="remember" type="checkbox"> Lembrar-me
        </label>
      </div>
      <button class="w-100 btn btn-lg btn-primary" type="submit">Entrar</button>

      <p class="mt-5 mb-3 text-muted">Sistema © {% now 'Y' %}</p>
    </form>
  </main>

<script>

window.onload = () => {
  document.getElementsByName("email")[0].value = localStorage.getItem("email");
  document.getElementById("remember").checked = localStorage.getItem("remember");
};

document.getElementById("login").onsubmit = () => {
  
    if(document.getElementById("remember").checked) {
      localStorage.setItem('email', document.getElementsByName("email")[0].value);
      localStorage.setItem('remember', document.getElementById("remember").checked);
    }else{
      localStorage.removeItem('email');
      localStorage.removeItem('remember');
    }

};

</script>

</body>

</html>